### ISSUE TITLE
这个安装依赖 install会失败啊  运行不起来  怎么搞

### ISSUE THREAD

**Issue by woshigelanren** [wuhou123/mui-vue2#1]

**Comment by woshigelanren** [comment]
这个安装依赖安装会失败啊运行不起来怎么搞

**Comment by wuhou123** [comment]
应该是网络问题，你试试cnpm

**Comment by encountermm** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-meituan@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-meituan@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\node\node_cache\_logs\2018-06-04T15_57_32_753Z-debug.log
