### ISSUE TITLE
字体图标出问题咋回事

### ISSUE THREAD

**Issue by yao727320796po** [wuhou123/mui-vue2#13]
Refused to load the image 'http://localhost:8080/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by wuhou123** [comment]
> Refused to load the image 'http://localhost:8080/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
这个是公用的图标，可以自己上传一个，或者不用管也可以
