### ISSUE TITLE
npm run dev 报的错误日志，该怎么解决呀

### ISSUE THREAD

**Issue by encountermm** [wuhou123/mui-vue2#3]
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\node\\node.exe',
1 verbose cli   'F:\\node\\node_global\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--userconfig=C:\\Users\\li112\\.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.8.0
3 info using node@v8.11.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-meituan@1.0.0~predev: vue-meituan@1.0.0
6 info lifecycle vue-meituan@1.0.0~dev: vue-meituan@1.0.0
7 verbose lifecycle vue-meituan@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-meituan@1.0.0~dev: PATH: F:\node\node_global\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;G:\mui-vue2\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\web\TortoiseGit\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;F:\git\cmd;F:\node\;C:\WINDOWS\System32\OpenSSH\;C:\Users\li112\AppData\Local\Microsoft\WindowsApps;D:\web\Egret Wing 3\bin;D:\web\Microsoft VS Code\bin;F:\node\node_global;
9 verbose lifecycle vue-meituan@1.0.0~dev: CWD: G:\mui-vue2
10 silly lifecycle vue-meituan@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
11 silly lifecycle vue-meituan@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle vue-meituan@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: vue-meituan@1.0.0 dev: `node build/dev-server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (F:\node\node_global\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (F:\node\node_global\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-meituan@1.0.0
15 verbose cwd G:\mui-vue2
16 verbose Windows_NT 10.0.17134
17 verbose argv "F:\\node\\node.exe" "F:\\node\\node_global\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\li112\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "dev"
18 verbose node v8.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-meituan@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue-meituan@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by wuhou123** [comment]
目测不是项目问题,你参考这个:https://segmentfault.com/q/1010000012749441
